[package]
name = "nyx-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = "0.20.0"
derive-new = "0.5.9"
derive_builder = "0.12.0"
getset = "0.1.0"

[build-dependencies]
lalrpop = "0.20.0"
